require('options')
require('plugins')
require('mappings')
require('treesitter-config')
require('lualine-config')
require('bufferline-config')
require('lexima-config')
require('onedark-config')
require('telescope-config')
require('telescope-extensions')
require('notify-extensions')
require('colorizer-config')
require('lsp')
require('lspsaga-config')
require("blankline-config")
require("toggleterm-config")
vim.cmd('colorscheme rose-pine')
