require('options')
require('plugins')
require('mappings')
require('treesitter-config')
require('lualine-config')
require('bufferline-config')
require('telescope-config')
require('onedark-config')
require('telescope-extensions')
require('notify-extensions')
require('colorizer-config')
require('lsp')
require('lspsaga-config')
require("blankline-config")
-- vim.cmd('colorscheme rose-pine')
-- vim.cmd('colorscheme gruvbox8_hard')
vim.cmd('colorscheme onedark')
--[[
moved these to lua/plugins/init.lua for supposedly a faster launch time
require("toggleterm-config")
require("lspkind-config")
]]
